#!/bin/bash -l
#SBATCH -A phys-743 
#SBATCH --reservation phys-743 -N 1 -n 20 -c 1 
#SBATCH --output=results_cg

srun valgrind --leak-check=full --track-origins=yes ./conjugategradient lap2D_5pt_n100.mtx
